### ISSUE TITLE
Logic User and Test

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#22]
:clock1: **6h**

Finish model + controller + view

**Comment by younos** [comment]
### How the users controller is working now

When you are a user which is not logged in:

* When requesting the index --> accepted
* When requesting the show view of a fighter --> accepted
* When requesting the show view of an admin or a gambler --> refused, redirection to the user index
* When requesting the edit view of any user --> refused, redirection to the sign_in page
* When making a PUT request (update) on any user --> refused, redirection to the sign_in page
* When making a DELETE request (destroy) on any user --> refused, redirection to the sign_in page

When you are a fighter/gambler logged in:

* When requesting the index --> accepted
* When requesting the show view of a fighter --> accepted
* When requesting the show view of an admin or a gambler --> refused (except himself), redirection to the user index
* When requesting the edit view of any user --> refused (except himself), redirection to his edit registration page
* When making a PUT request (update) on any user --> refused (except himself), redirection to his edit registration page
* When making a DELETE request (destroy) on any user --> refused, redirection to his edit registration page

When you are an admin logged in:

* When requesting the index --> accepted
* When requesting the show view of any user --> accepted
* When requesting the edit view of any user --> accepted
* When making a PUT request (update) on any user --> accepted
* When making a DELETE request (destroy) on any user --> accepted (except himself)

### A remark

When any user want to edit his **own** registration/account, you are redirected to "/users/edit", which corresponds to the devise view "devise.registrations.edit.html.haml".
But when an admin want to edit the registration/account of another user, he is redirected to /users/:id/edit, which corresponds to the user view "users.edit.hmtl.haml".

### TODO
* See if all the redirections are consistent
* Make a partial, e.g. "_form.html.haml", in order to avoid repetitions between the views "users.edit.hmtl.haml" and "devise.registrations.edit.html.haml"
* Find a mean to update the account of a user without allowing some parameters in the POST request (see the TODO of the method "users_params" in the users controller)
* ...

**Comment by Nikowned** [comment]
:clock1: **[8]h**
