### ISSUE TITLE
Highlight required fields in forms

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#36]

**Comment by tibm** [comment]
Just add: `.required`class to your `label`.
For nice view: once a user submitted a form and a field was missing or had an error it is nice that that field is highlighted. With our design we need to do that manually (simple_form_for cannot handle it because of our design). So do the following:

`%label.fa.fa-icon-you-want.required{class: ('error' if value_missing)}

**Comment by samtdr** [comment]
@tibm  I've added the "highlighting error fields". but for the wallet#load or refund page:
I figured the way that transaction controller is written, there's no (@transaction)model validation happening, thus no errors is being sent from controller to the view. I've spent to 3-4 hours fix this, but no luck. Maybe you if you have time, you can help me. thanks :)

**Comment by sebyx31** [comment]
Validation in transaction model is scheduled in #71.

**Comment by sebyx31** [comment]
:clock1: **2h**

**Comment by samtdr** [comment]
@sebyx31 I think there were some work left (for credit form), so I continued your work and edited paypal.rb and transaction_controller a bit more. and I think now its finished. Can please check it and if there was no new problem, close the issue?

**Comment by tibm** [comment]
@sebyx31 @samtdr is this issue done? Because i would like to close all issues for tomorrow. Project needs to see it's end! We need to deploy a final Version on heroku at latest tomorrow for final checking!

**Comment by samtdr** [comment]
2h
@sebyx31 @tibm  I was waiting to see if there'e any bug about it, apparently there isn't :) I'm closing the issue.
